require_relative('../models/categories.rb')
require_relative('../models/types.rb')
require_relative('../models/items.rb')
require_relative('./seeds-categories.rb')
require_relative('./seeds-types.rb')
require_relative('./seeds-items.rb')
require_relative('./seeds-cclasses.rb')
